# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stuff
subtitle: // TODO replace this code with something better
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Things that I cannot remember but may sometimes need.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scottwhittaker.github.io" # the base hostname & protocol for your site

gems: [jekyll-paginate]

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: _sass
  style: compressed
paginate: 5
